/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./template-parts/**/*.{php,html,js}","./*.{php,html,js}"],
  theme: {
    extend: {},
    fontFamily: {
      'serif': ['Capito', 'serif'],
      'sans': ['National', 'sans-serif'],
    },
    colors: {
      'primary': '#1d4b67',
      'secondary': '#eda600',
      'tertiary': '#0171b1',
      'gray': '#5b5b5b',
      'white': '#fff',
    },
    container: {
      center: true,

      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1200px',
        '2xl': '1200px',
      },
    },
    'container-wide': {
      center: true,
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1400px',
        '2xl': '1400px',
      },
    }
  },
  safelist: [
    'lg:justify-start',
    'lg:justify-end',
    'lg:justify-center',
    'cursor-pointer',
    'flex-row',
    'flex-col',
    'flex-row-reverse',
    'lg:flex-row-reverse',
    'lg:flex-row',
    'lg:text-center',
    'md:text-4xl',
    'p-48',
    'p-8',
    'pb-4',
    'pb-12',
    'px-12',
    'py-12',
    'w-7/12',
    'rounded-lg',
    'rounded-md',
    'mb-0',
    'mb-6',
    'mb-16',
    'mt-6',
    'my-6',
    'text-gray',
    'text-lg',
    'mc-block-link',
    'min-h-[700px]',
    'underline',
    'md:w-7/12',
    'md:mb-16',
    'md:text-left',
    'mb-8',
    'text-3xl',
    'mc-btn-primary',
  ],
  plugins: [],
  module: {},
  important: true,
}

